export const ERROR_TYPES = {
  UNKNOWN_ERROR: "Some error occured. Please try later !",
  FAILED_GOOGLE_AUTH: "Couldn't authenticate with Google !",
  USER_ALREADY_EXIST: "User already exists !",
  INVALID_CREDENTIALS: "Invalid credentials !",
  USER_DOESNT_EXIST: "User doesn't exist !",
  PASSWORD_DOESNT_MATCH: "Password does not match",
  GET_POSTS: "Some error occured while fetching memories. Please refresh !",
  GET_POST: "Some error occured while fetching memory. Please refresh !",
  CREATE_POST: "Couldn't create a memory. Try again !",
  UPDATE_POST: "Couldn't update the memory. Try again !",
  DELETE_POST: "Couldn't delete the memory. Try again !",
  LIKE_POST: "Couldn't like the memory. Try again !",
  NO_POSTS: "No posts found !",
};
